name: Deploy Infrastructure

on:
  push:
    branches:
      - master

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET }}

jobs:
  deploy_infrastructure:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: infrastructure

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 0.14.7

    - name: Initialization Terraform
      run: terraform init
    
    - name: Validate Terraform configuration
      run: terraform validate

    - name: Deploy Terraform
      run: terraform apply -auto-approve